# Generated by Django 5.0 on 2024-02-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_tagrating_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='company_images/'),
        ),
    ]
