# Generated by Django 5.0 on 2024-02-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_company_github_alter_company_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, default='img/default_image.jpg', null=True, upload_to='company_images/'),
        ),
    ]
